Dqn implementation
Thurstag/survaillant-ais pull request #15
Opened 2021-12-19 22:49 UTC by Fantorem

2021-12-20 16:57 UTC, Thurstag requested changes

2021-12-20 16:57 UTC, Thurstag commented on src/common/states.js
> +/**
Fichier à supprimer

2021-12-20 16:57 UTC, Thurstag commented on package.json
> +        "@tensorflow/tfjs-node": "^2.8.6",
A revert

2021-12-20 16:57 UTC, Thurstag commented on package.json
> +        "@tensorflow/tfjs-node-gpu": "^2.8.6",
A revert

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +    parser.add_argument("--actions", {
A supprimer, l'utilisateur ne doit pas choisir

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +        const statsFile = join(statsFolder, "DQN.csv");
A renommer car on perd toutes les infos de training

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +        await env.stats.writeTo(statsFile);
Tu peux utiliser `GamesStats.writeTo` car il faut exporter aussi les epochs

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +            await network.saveTo(name => `.${sep}${name}${SurvaillantTrainingNetwork.SAVED_MODEL_EXTENSION}`, metadata, "file");
Sachant qu'une epoch est rapide autant sauvegarder toutes les x epochs. La sauvegarde du network doit surement ralentir le training

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +    const stateGenerator = new FlashlightStateGenerator(4, representation);
On a pas le choix du state generator et des paramètres liés à celui-ci

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +    parser.add_argument("--height", {
C'est pas à l'utilisateur de le spécifier sauf si on est en mode normal

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +    parser.add_argument("--width", {
Pareil

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +        help: "Representation of the game's state ()"
Parenthèse vide

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +        default: "./models/dqn",
default à enlever, tu informes même pas l'utilisateur durant le training où le network est sauvegardé

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/agent.js
> +        let old = 100000;
L'utilisateur n'a pas le choix sur le nombre d'epochs

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/agent.js
> +                if (frameCount < this.config.espilonRanomFrames || this.config.epsilon > Math.random()) {
`this.config.epsilonRandomFrames`

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +    parser.add_argument("--espilonGreedyFrames", {
epsilonGreedyFrames

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +    parser.add_argument("--espilonRandomFrames", {
epsilonRandomFrames

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +    await loadTfBackend(BACKEND.CPU);
L'utilisateur a pas le choix

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/train.js
> +        type: "str",
`type: path`

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/network.js
> + * Create a training PPO network with existing networks
PPO ???

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/network.js
> +    model.add(tf.layers.dense({ units: SurvaillantTrainingNetwork.ACTIONS_COUNT }));
`keras.dense`

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/network.js
> +    model.add(tf.layers.dense({ units: 100, activation: "relu" }));
`keras.dense`

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/network.js
> +    model.add(tf.layers.conv2d({
`keras.conv2d`

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/network.js
> +    model.add(tf.layers.conv2d({
`keras.conv2d`

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/network.js
> +    model.add(tf.layers.conv2d({
`keras.conv2d`

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/network.js
> +        return super.network("dqnPolicy");
`return super.network(POLICY_NETWORK_NAME)`

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/agent.js
> +            LOGGER.info("Score: " + episodeReward +  "  at epoche " + `${episodeCount}/${old}` + " with " + stepCount + " steps");
epoch

2021-12-20 16:57 UTC, Thurstag commented on src/dqn/agent.js
> +                if (rewardsHistory.length > this.config.maxMemoryLength) {
La memory leak vient surement d'ici

2021-12-20 20:38 UTC, Fantorem commented on src/dqn/train.js
> +        await env.stats.writeTo(statsFile);
env.stats retourne GameStats

2021-12-21 13:40 UTC, Thurstag commented on src/dqn/train.js
> +        await env.stats.writeTo(statsFile);
regardes le PPO

2021-12-31 14:46 UTC, Thurstag requested changes

2021-12-31 14:46 UTC, Thurstag commented on test/train/index.spec.js
> +    it("Train an existing DQN network", async function () {
Sert à rien, ton script peut pas entrainer un network existant

2022-01-05 23:06 UTC, Thurstag requested changes

2022-01-05 23:06 UTC, Thurstag commented on test/train/index.spec.js
> +            it(`Train DQNs network (policy: ${rewardPolicy}, representation: exhaustive, state: ${state})`, async function () {
Tu testes plus les représentations real et summary

2022-01-05 23:06 UTC, Thurstag commented on test/train/index.spec.js
> +const PPO_EPOCHS = 2, DDPG_EPOCHS = 2, DQN_EPOCHES = 20;
`DDPG_EPOCHS = 2` => a revert

2022-01-07 14:44 UTC, Thurstag requested changes

2022-01-07 14:44 UTC, Thurstag commented on src/dqn/agent.js
> +        this.model = fromZero(env.stateShape.x, env.stateShape.y, env.stateShape.z);
A enlever, tu écrases les modèles chargés

2022-01-07 17:14 UTC, merged